apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
patches:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - hpa-patch.yaml
images:
  - name: 192.168.30.11:30002/library/myapp
    newTag: v1.0.0
configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - app_env=staging
      - log_level=info
